/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AjustesRouteImport } from './routes/ajustes'
import { Route as BienvenidaRouteImport } from './routes/bienvenida'
import { Route as CuentaRouteImport } from './routes/cuenta'
import { Route as CuentosRouteImport } from './routes/cuentos'
import { Route as EntradaRouteImport } from './routes/entrada'
import { Route as HistorialRouteImport } from './routes/historial'
import { Route as InvitacionRouteImport } from './routes/invitacion'
import { Route as MaterialesRouteImport } from './routes/materiales'
import { Route as VerificarRouteImport } from './routes/verificar'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminIdRouteImport } from './routes/admin.$id'
import { Route as AdminUsoRouteImport } from './routes/admin.uso'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as CuentoIdRouteImport } from './routes/cuento.$id'
import { Route as CuentoPedidoRouteImport } from './routes/cuento.pedido'
import { Route as FamiliaIndexRouteImport } from './routes/familia.index'
import { Route as FamiliaContanosRouteImport } from './routes/familia.contanos'
import { Route as FamiliaCorregirRouteImport } from './routes/familia.corregir'
import { Route as FamiliaRevisarRouteImport } from './routes/familia.revisar'
import { Route as JuguetesIndexRouteImport } from './routes/juguetes.index'
import { Route as JuguetesIdRouteImport } from './routes/juguetes.$id'
import { Route as CuentoTemaKeywordRouteImport } from './routes/cuento.tema.$keyword'
import { Route as IdeaIdIndexRouteImport } from './routes/idea.$id.index'
import { Route as IdeaIdQueSuenaRouteImport } from './routes/idea.$id.que-suena'
import { Route as IdeaIdRelojRouteImport } from './routes/idea.$id.reloj'
import { Route as SerieIdIndexRouteImport } from './routes/serie.$id.index'
import { Route as SerieIdEpisodioRouteImport } from './routes/serie.$id.episodio'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
})
const AjustesRoute = AjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => rootRouteImport,
})
const BienvenidaRoute = BienvenidaRouteImport.update({
  id: '/bienvenida',
  path: '/bienvenida',
  getParentRoute: () => rootRouteImport,
})
const CuentaRoute = CuentaRouteImport.update({
  id: '/cuenta',
  path: '/cuenta',
  getParentRoute: () => rootRouteImport,
})
const CuentosRoute = CuentosRouteImport.update({
  id: '/cuentos',
  path: '/cuentos',
  getParentRoute: () => rootRouteImport,
})
const EntradaRoute = EntradaRouteImport.update({
  id: '/entrada',
  path: '/entrada',
  getParentRoute: () => rootRouteImport,
})
const HistorialRoute = HistorialRouteImport.update({
  id: '/historial',
  path: '/historial',
  getParentRoute: () => rootRouteImport,
})
const InvitacionRoute = InvitacionRouteImport.update({
  id: '/invitacion',
  path: '/invitacion',
  getParentRoute: () => rootRouteImport,
})
const MaterialesRoute = MaterialesRouteImport.update({
  id: '/materiales',
  path: '/materiales',
  getParentRoute: () => rootRouteImport,
})
const VerificarRoute = VerificarRouteImport.update({
  id: '/verificar',
  path: '/verificar',
  getParentRoute: () => rootRouteImport,
})
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
})
const AdminIdRoute = AdminIdRouteImport.update({
  id: '/admin/$id',
  path: '/admin/$id',
  getParentRoute: () => rootRouteImport,
})
const AdminUsoRoute = AdminUsoRouteImport.update({
  id: '/admin/uso',
  path: '/admin/uso',
  getParentRoute: () => rootRouteImport,
})
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/admin/usuarios',
  path: '/admin/usuarios',
  getParentRoute: () => rootRouteImport,
})
const CuentoIdRoute = CuentoIdRouteImport.update({
  id: '/cuento/$id',
  path: '/cuento/$id',
  getParentRoute: () => rootRouteImport,
})
const CuentoPedidoRoute = CuentoPedidoRouteImport.update({
  id: '/cuento/pedido',
  path: '/cuento/pedido',
  getParentRoute: () => rootRouteImport,
})
const FamiliaIndexRoute = FamiliaIndexRouteImport.update({
  id: '/familia/',
  path: '/familia/',
  getParentRoute: () => rootRouteImport,
})
const FamiliaContanosRoute = FamiliaContanosRouteImport.update({
  id: '/familia/contanos',
  path: '/familia/contanos',
  getParentRoute: () => rootRouteImport,
})
const FamiliaCorregirRoute = FamiliaCorregirRouteImport.update({
  id: '/familia/corregir',
  path: '/familia/corregir',
  getParentRoute: () => rootRouteImport,
})
const FamiliaRevisarRoute = FamiliaRevisarRouteImport.update({
  id: '/familia/revisar',
  path: '/familia/revisar',
  getParentRoute: () => rootRouteImport,
})
const JuguetesIndexRoute = JuguetesIndexRouteImport.update({
  id: '/juguetes/',
  path: '/juguetes/',
  getParentRoute: () => rootRouteImport,
})
const JuguetesIdRoute = JuguetesIdRouteImport.update({
  id: '/juguetes/$id',
  path: '/juguetes/$id',
  getParentRoute: () => rootRouteImport,
})
const CuentoTemaKeywordRoute = CuentoTemaKeywordRouteImport.update({
  id: '/cuento/tema/$keyword',
  path: '/cuento/tema/$keyword',
  getParentRoute: () => rootRouteImport,
})
const IdeaIdIndexRoute = IdeaIdIndexRouteImport.update({
  id: '/idea/$id/',
  path: '/idea/$id/',
  getParentRoute: () => rootRouteImport,
})
const IdeaIdQueSuenaRoute = IdeaIdQueSuenaRouteImport.update({
  id: '/idea/$id/que-suena',
  path: '/idea/$id/que-suena',
  getParentRoute: () => rootRouteImport,
})
const IdeaIdRelojRoute = IdeaIdRelojRouteImport.update({
  id: '/idea/$id/reloj',
  path: '/idea/$id/reloj',
  getParentRoute: () => rootRouteImport,
})
const SerieIdIndexRoute = SerieIdIndexRouteImport.update({
  id: '/serie/$id/',
  path: '/serie/$id/',
  getParentRoute: () => rootRouteImport,
})
const SerieIdEpisodioRoute = SerieIdEpisodioRouteImport.update({
  id: '/serie/$id/episodio',
  path: '/serie/$id/episodio',
  getParentRoute: () => rootRouteImport,
})

const rootRouteChildren = {
  IndexRoute: IndexRoute,
  AjustesRoute: AjustesRoute,
  BienvenidaRoute: BienvenidaRoute,
  CuentaRoute: CuentaRoute,
  CuentosRoute: CuentosRoute,
  EntradaRoute: EntradaRoute,
  HistorialRoute: HistorialRoute,
  InvitacionRoute: InvitacionRoute,
  MaterialesRoute: MaterialesRoute,
  VerificarRoute: VerificarRoute,
  AdminIdRoute: AdminIdRoute,
  AdminUsoRoute: AdminUsoRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  CuentoIdRoute: CuentoIdRoute,
  CuentoPedidoRoute: CuentoPedidoRoute,
  FamiliaContanosRoute: FamiliaContanosRoute,
  FamiliaCorregirRoute: FamiliaCorregirRoute,
  FamiliaRevisarRoute: FamiliaRevisarRoute,
  JuguetesIdRoute: JuguetesIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  FamiliaIndexRoute: FamiliaIndexRoute,
  JuguetesIndexRoute: JuguetesIndexRoute,
  CuentoTemaKeywordRoute: CuentoTemaKeywordRoute,
  IdeaIdQueSuenaRoute: IdeaIdQueSuenaRoute,
  IdeaIdRelojRoute: IdeaIdRelojRoute,
  SerieIdEpisodioRoute: SerieIdEpisodioRoute,
  IdeaIdIndexRoute: IdeaIdIndexRoute,
  SerieIdIndexRoute: SerieIdIndexRoute,
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)
